const ADD_MOVIE = 'ADD_MOVIE'
const DELETE_MOVIE = 'DELETE_MOVIE'
const UPDATE_MOVIE = 'UPDATE_MOVIE'
const RESET_MOVIES = 'RESET_MOVIES'

export default {
    ADD_MOVIE,
    DELETE_MOVIE,
    UPDATE_MOVIE,
    RESET_MOVIES
}