const ADD_ACTOR = 'ADD_ACTOR'
const DELETE_ACTOR = 'DELETE_ACTOR'
const UPDATE_ACTOR = 'UPDATE_ACTOR'
const RESET_ACTORS = 'RESET_ACTORS'

export default {
    ADD_ACTOR,
    DELETE_ACTOR,
    UPDATE_ACTOR,
    RESET_ACTORS
}